using Inteldev.Core.DTO;
using Inteldev.Core.DTO.Locacion;
using Inteldev.Core.DTO.Organizacion;
using Inteldev.Core.DTO.Usuarios;
using Inteldev.Core.Presentacion;
using Inteldev.Core.Presentacion.Controles;
using Inteldev.Core.Presentacion.Vistas;
using Inteldev.Fixius.Articulos.Maestro;
using Inteldev.Fixius.Articulos.Tablas.AreaSectorFamilia;
using Inteldev.Fixius.Articulos.Tablas.Categoria;
using Inteldev.Fixius.Articulos.Tablas.Envase;
using Inteldev.Fixius.Articulos.Tablas.GrupoArticulo;
using Inteldev.Fixius.Articulos.Tablas.SKU;
using Inteldev.Fixius.Clientes.Maestro;
using Inteldev.Fixius.Clientes.Tablas.CondicionDePagoCliente;
using Inteldev.Fixius.Clientes.Tablas.Grupo;
using Inteldev.Fixius.Clientes.Tablas.Ramo;
using Inteldev.Fixius.Clientes.Tablas.TarjetaMayorista;
using Inteldev.Fixius.Deposito;
using Inteldev.Fixius.Deposito.IngresoMercaderia;
using Inteldev.Fixius.Logistica;
using Inteldev.Fixius.Organizacion;
using Inteldev.Fixius.Organizacion.Calle;
using Inteldev.Fixius.Organizacion.Localidad;
using Inteldev.Fixius.Organizacion.Provincia;
using Inteldev.Fixius.Organizacion.Usuarios;
using Inteldev.Fixius.Preventa;
using Inteldev.Fixius.Preventa.DescuentosPorLista;
using Inteldev.Fixius.Preventa.FuerzaDeVenta.Cobrador;
using Inteldev.Fixius.Preventa.FuerzaDeVenta.Jefe;
using Inteldev.Fixius.Preventa.FuerzaDeVenta.Preventista;
using Inteldev.Fixius.Preventa.FuerzaDeVenta.Supervisor;
using Inteldev.Fixius.Preventa.GeoRegion;
using Inteldev.Fixius.Preventa.HabilitacionDeListas;
using Inteldev.Fixius.Preventa.ListaDePrecios;
using Inteldev.Fixius.Preventa.Precios.CambioDePrecios;
using Inteldev.Fixius.Preventa.RegionDeVenta;
using Inteldev.Fixius.Preventa.Vendedor;
using Inteldev.Fixius.Proveedores.Colores;
using Inteldev.Fixius.Proveedores.Compras.ListaDePrecios;
using Inteldev.Fixius.Proveedores.Compras.ObjetivosDeCompra;
using Inteldev.Fixius.Proveedores.Compras.OrdenDeCompra;
using Inteldev.Fixius.Proveedores.Compras.PlantillaListaDePrecios;
using Inteldev.Fixius.Proveedores.CuenasAPagar.CargaComprobantes;
using Inteldev.Fixius.Proveedores.CuenasAPagar.OrdenDePago;
using Inteldev.Fixius.Proveedores.CuentasAPagar.CargaComprobantes;
using Inteldev.Fixius.Proveedores.MaestroProveedor;
using Inteldev.Fixius.Proveedores.Tablas.CondicionDePago;
using Inteldev.Fixius.Servicios.DTO.Articulos;
using Inteldev.Fixius.Servicios.DTO.Clientes;
using Inteldev.Fixius.Servicios.DTO.Financiero;
using Inteldev.Fixius.Servicios.DTO.Precios;
using Inteldev.Fixius.Servicios.DTO.Proveedores;
using Inteldev.Fixius.Servicios.DTO.Stock;
using Inteldev.Fixius.Servicios.DTO.Tesoreria;
using Inteldev.Fixius.Tesoreria;
using Inteldev.Fixius.Tesoreria.ChequeTerceros;

namespace Inteldev.Fixius.Vistas
{
    /// <summary>
    /// Contiene el registro de las vistas a usar para cada unidad de negocio.
    /// Cuando se carga una vista, si no se especifica la unidad, se toma para todos.
    /// </summary>
    public class RegistroVistas : RegistroFabricaVistas
    {
        public override void Registrar()
        {
            this.Registro(typeof(PerfilUsuario), UnidadeDeNegocio.Mayorista, typeof(VistaPerfilUsuario));
            this.Registro(typeof(PerfilUsuario), typeof(VistaPerfilUsuario));
            this.Registro(typeof(Usuario), typeof(VistaUsuario));
            this.Registro(typeof(Localidad), typeof(VistaLocalidad));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Empaque), typeof(Inteldev.Fixius.Articulos.Tablas.Empaque));
            this.Registro(typeof(Envase), typeof(VistaEnvase));
            this.Registro(typeof(Categoria), typeof(VistaCategoria));
            this.Registro(typeof(GrupoArticulo), typeof(VistaGrupoArticulo));
            this.Registro(typeof(Caracteristica), typeof(Inteldev.Fixius.Articulos.Tablas.Caracteristica.VistaCaracteristica));
            this.Registro(typeof(Marca), typeof(Inteldev.Fixius.Articulos.Tablas.Marca.VistaMarca));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Proveedores.CondicionDePagoProveedor), typeof(VistaCondicionDePago));
            this.Registro(typeof(Entrega), typeof(VistaEntrega));
            this.Registro(typeof(ConceptoDeMovimiento), typeof(EntidadMaestro));
            this.Registro(typeof(Jerarquia), typeof(EntidadMaestro));
            this.Registro(typeof(Proveedor), typeof(VistaProveedor));
            this.Registro(typeof(Articulo), typeof(VistaArticulo));
            this.Registro(typeof(Calle), typeof(VistaCalle));
            this.Registro(typeof(Provincia), typeof(VistaProvincia));
            //       this.Registro(typeof(Cliente), UnidadeDeNegocio.Mayorista, typeof(Inteldev.Fixius.Clientes.Maestro.Mayorista.VistaCliente));
            this.Registro(typeof(Cliente), typeof(VistaCliente));
            this.Registro(typeof(PlantillaListaProveedor), typeof(VistaPlantillaDePrecios));
            this.Registro(typeof(ListaDePrecios), typeof(VistaListaDePreciosProveedor));
            this.Registro(typeof(TarjetaClienteMayorista), typeof(VistaTarjetaMayorista));
            this.Registro(typeof(Ramo), typeof(VistaRamo));
            this.Registro(typeof(GrupoCliente), typeof(VistaGrupo));
            //this.Registro(typeof(TasasDeIva), typeof(ItemTasaDeIva));
            this.Registro(typeof(ObjetivosDeCompra), typeof(VistaObjetivosDeCompra));
            this.Registro(typeof(Core.DTO.Stock.Deposito), typeof(VistaDeposito));
            this.Registro(typeof(ListaDePreciosDeVenta), typeof(VistaListeDePreciosDeVenta));
            this.Registro(typeof(ColorColumnaPlantilla), typeof(SeleccionaColor));
            this.Registro(typeof(HabilitaLista), typeof(VistaHabiltaLista));
            this.Registro(typeof(Inteldev.Core.DTO.Organizacion.DivisionComercial), typeof(Fixius.Organizacion.DivisionComercial));
            this.Registro(typeof(Sucursal), typeof(EntidadMaestro));
            this.Registro(typeof(Empresa), typeof(VistaEmpresa));
            this.Registro(typeof(DescuentosPorLista), typeof(VistaDescuentosPorLista));
            this.Registro(typeof(OrdenDeCompra), typeof(VistaOrdenCompra));
            this.Registro(typeof(CambioDePreciosDeVenta), typeof(VistaCambioDePreciosDeVenta));
            this.Registro(typeof(Ingreso), typeof(VistaIngreso));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Stock.ConceptoDeMovimientoDeStock), typeof(Inteldev.Fixius.Deposito.ConceptoDeMovimientoDeStock));
            this.Registro(typeof(Transportista), typeof(EntidadMaestro));
            this.Registro(typeof(Banco), typeof(VistaBanco));
            this.Registro(typeof(TipoProveedor), typeof(EntidadMaestro));
            this.Registro(typeof(Clase), typeof(Inteldev.Fixius.Articulos.Tablas.Clase.VistaClase));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Rubro), typeof(Fixius.Articulos.Tablas.Rubro.Rubro));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Division), typeof(Inteldev.Fixius.Articulos.Tablas.Division.VistaDivision));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Linea), typeof(Fixius.Articulos.Tablas.Linea.Linea));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.Canal), typeof(EntidadMaestro));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.RutaDeVenta), typeof(Inteldev.Fixius.Preventa.RutaDeVenta.VistaRutaDeVenta));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.CargosDeFuerzaDeVenta), typeof(VistaCargos));
            //this.Registro(typeof(Servicios.DTO.Proveedores.DocumentoCompra), typeof(VistaDocumentoCompra));
            //this.Registro(typeof(Servicios.DTO.Proveedores.DocumentoCompra), typeof(VistaCargaDocumentoCompra));
            this.Registro(typeof(Servicios.DTO.Proveedores.DocumentoCompra), typeof(CabeceraDocumentoDeCompra));
            this.Registro(typeof(Servicios.DTO.Proveedores.OrdenDePago), typeof(VistaOrdenDePago));
            this.Registro(typeof(Servicios.DTO.Tesoreria.ChequeDeTercero), typeof(VistaChequeTerceros));
            this.Registro(typeof(Servicios.DTO.Logistica.ZonaGeografica), typeof(VistaZonaGeografica));
            this.Registro(typeof(Servicios.DTO.Logistica.ZonaLogistica), typeof(VistaZonaLogistica));
            this.Registro(typeof(Servicios.DTO.Preventa.Jefe), typeof(VistaJefe));
            this.Registro(typeof(Servicios.DTO.Preventa.Supervisor), typeof(VistaSupervisores));
            this.Registro(typeof(Servicios.DTO.Preventa.Preventista), typeof(VistaPreventista));
            this.Registro(typeof(Servicios.DTO.Preventa.Cobrador), typeof(VistaCobrador));
            this.Registro(typeof(Servicios.DTO.Preventa.Vendedor), typeof(VistaVendedor));
            this.Registro(typeof(Servicios.DTO.Tesoreria.CuentaBancaria), typeof(Inteldev.Fixius.Tesoreria.CuentaBancaria.CuentaBancaria));
            this.Registro(typeof(Servicios.DTO.Tesoreria.ConceptoDeMovimientoBancario), typeof(Inteldev.Fixius.Tesoreria.MovimientoBancario.ConceptoMovimientoBancario));
            this.Registro(typeof(Servicios.DTO.Proveedores.ResponsablesCompras), typeof(EntidadMaestro));
            this.Registro(typeof(Servicios.DTO.Clientes.CondicionDePagoCliente), typeof(VistaCondicionDePagoCliente));
            this.Registro(typeof(Servicios.DTO.Articulos.SKU), typeof(VistaSKU));
            this.Registro(typeof(Servicios.DTO.Clientes.RegionDeVenta), typeof(VistaRegionDeVenta));
            this.Registro(typeof(Servicios.DTO.Clientes.GeoRegionDeVenta), typeof(VistaGeoRegion));

            this.Registro(typeof(Servicios.DTO.Articulos.Area), typeof(VistaArea));
            this.Registro(typeof(Servicios.DTO.Articulos.Sector), typeof(VistaSector));
            this.Registro(typeof(Servicios.DTO.Articulos.Subsector), typeof(VistaSubSector));
            this.Registro(typeof(Servicios.DTO.Articulos.Familia), typeof(VistaFamilia));
            this.Registro(typeof(Servicios.DTO.Articulos.Subfamilia), typeof(VistaSubFamilia));

            #region Listados
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Rubro), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Usuario), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Localidad), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Empaque), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Envase), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Categoria), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(GrupoArticulo), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Caracteristica), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Marca), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Proveedores.CondicionDePagoProveedor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Entrega), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(ConceptoDeMovimiento), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Jerarquia), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Calle), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Provincia), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(PlantillaListaProveedor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(ListaDePrecios), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(TarjetaClienteMayorista), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Ramo), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(GrupoCliente), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(ObjetivosDeCompra), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Core.DTO.Stock.Deposito), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(ListaDePreciosDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(ColorColumnaPlantilla), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(HabilitaLista), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Core.DTO.Organizacion.DivisionComercial), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Sucursal), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Empresa), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(DescuentosPorLista), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(OrdenDeCompra), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(CambioDePreciosDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Ingreso), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Stock.ConceptoDeMovimientoDeStock), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Transportista), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Banco), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(TipoProveedor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Proveedor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Clase), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Division), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Articulos.Linea), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.Canal), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.RutaDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Inteldev.Fixius.Servicios.DTO.Clientes.CargosDeFuerzaDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Proveedores.DocumentoCompra), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Proveedores.OrdenDePago), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Tesoreria.ChequeDeTercero), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Logistica.ZonaGeografica), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Preventa.Jefe), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Preventa.Supervisor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Preventa.Preventista), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Preventa.Cobrador), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Preventa.Vendedor), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Tesoreria.CuentaBancaria), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Tesoreria.ConceptoDeMovimientoBancario), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Proveedores.ResponsablesCompras), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Clientes.CondicionDePagoCliente), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.SKU), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Clientes.RegionDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Clientes.GeoRegionDeVenta), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.Area), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.Sector), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.Subsector), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.Familia), TipoVista.Listado, typeof(Listado));
            this.Registro(typeof(Servicios.DTO.Articulos.Subfamilia), TipoVista.Listado, typeof(Listado));
            #endregion
        }
    }
}
