//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inteldev.Fixius.ServiceMobile {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.inteldevmobile.com.ar", ConfigurationName="ServiceMobile.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/validarConeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validarConeccion(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/dameDistri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string dameDistri(string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosCliente(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosCliente(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirNewConvenios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirNewConvenios(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirNewPrecios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirNewPrecios(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosMobile(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosMobile(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosCliente2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosCliente2(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosCliente3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosCliente3(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosCliente4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosCliente4(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosCliente2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosCliente2(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosMobile2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosMobile2(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosCliente3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosCliente3(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosMobile3parte1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosMobile3parte1(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosMobile3parte2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosMobile3parte2(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/bajarDatosMobileZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string bajarDatosMobileZip(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosMobile2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosMobile2(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/subirDatosMobile3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string subirDatosMobile3(string usuario, string clave, string imei, string xmlDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/execQueryReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string execQueryReturn(string miQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/actualizaFechaDownLoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualizaFechaDownLoad(string usuario, string clave, string imei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/borraXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string borraXml(string cFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/hola", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string hola(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/CunsultarPorCodigoDeBarra2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CunsultarPorCodigoDeBarra2(string codigobarra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/devuelvefecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string devuelvefecha();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ActualizarPosicion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarPosicion(string usuario, string fecha, string lat, string lng, int estado, string cliente, int motivonocompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ActualizarPosicionTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarPosicionTest(string usuario, string fecha, string lat, string lng, int estado, string cliente, int motivonocompra, string pesos, int bultos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ActualizarLastDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarLastDownload(string imei, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ActualizarLastDownloadATodas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarLastDownloadATodas(string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ObtenerPosicionActualPreventistas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerPosicionActualPreventistas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ObtenerPosicionesDelPreventista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerPosicionesDelPreventista(string usuario, System.DateTime fechaDesde, System.DateTime fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ObtenerVendedoresPorDia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerVendedoresPorDia(System.DateTime fechaDesde, System.DateTime fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ObtenerPrimerClienteVisitado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerPrimerClienteVisitado(string usuario, System.DateTime fechaDesde, System.DateTime fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/ObtenerPreventistasPorEmpresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerPreventistasPorEmpresa(string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inteldevmobile.com.ar/SubirFotoCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubirFotoCliente(string usuario, string cliente, string foto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Inteldev.Fixius.ServiceMobile.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Inteldev.Fixius.ServiceMobile.ServiceSoap>, Inteldev.Fixius.ServiceMobile.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validarConeccion(string usuario, string clave, string imei) {
            return base.Channel.validarConeccion(usuario, clave, imei);
        }
        
        public string dameDistri(string imei) {
            return base.Channel.dameDistri(imei);
        }
        
        public string bajarDatosCliente(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosCliente(usuario, clave, imei);
        }
        
        public string subirDatosCliente(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosCliente(usuario, clave, imei, xmlDatos);
        }
        
        public string subirNewConvenios(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirNewConvenios(usuario, clave, imei, xmlDatos);
        }
        
        public string subirNewPrecios(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirNewPrecios(usuario, clave, imei, xmlDatos);
        }
        
        public string bajarDatosMobile(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosMobile(usuario, clave, imei);
        }
        
        public string subirDatosMobile(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosMobile(usuario, clave, imei, xmlDatos);
        }
        
        public string bajarDatosCliente2(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosCliente2(usuario, clave, imei);
        }
        
        public string bajarDatosCliente3(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosCliente3(usuario, clave, imei);
        }
        
        public string bajarDatosCliente4(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosCliente4(usuario, clave, imei);
        }
        
        public string subirDatosCliente2(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosCliente2(usuario, clave, imei, xmlDatos);
        }
        
        public string bajarDatosMobile2(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosMobile2(usuario, clave, imei);
        }
        
        public string subirDatosCliente3(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosCliente3(usuario, clave, imei, xmlDatos);
        }
        
        public string bajarDatosMobile3parte1(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosMobile3parte1(usuario, clave, imei);
        }
        
        public string bajarDatosMobile3parte2(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosMobile3parte2(usuario, clave, imei);
        }
        
        public string bajarDatosMobileZip(string usuario, string clave, string imei) {
            return base.Channel.bajarDatosMobileZip(usuario, clave, imei);
        }
        
        public string subirDatosMobile2(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosMobile2(usuario, clave, imei, xmlDatos);
        }
        
        public string subirDatosMobile3(string usuario, string clave, string imei, string xmlDatos) {
            return base.Channel.subirDatosMobile3(usuario, clave, imei, xmlDatos);
        }
        
        public string execQueryReturn(string miQuery) {
            return base.Channel.execQueryReturn(miQuery);
        }
        
        public string actualizaFechaDownLoad(string usuario, string clave, string imei) {
            return base.Channel.actualizaFechaDownLoad(usuario, clave, imei);
        }
        
        public string borraXml(string cFile) {
            return base.Channel.borraXml(cFile);
        }
        
        public string hola(string mensaje) {
            return base.Channel.hola(mensaje);
        }
        
        public string CunsultarPorCodigoDeBarra2(string codigobarra) {
            return base.Channel.CunsultarPorCodigoDeBarra2(codigobarra);
        }
        
        public string devuelvefecha() {
            return base.Channel.devuelvefecha();
        }
        
        public string ActualizarPosicion(string usuario, string fecha, string lat, string lng, int estado, string cliente, int motivonocompra) {
            return base.Channel.ActualizarPosicion(usuario, fecha, lat, lng, estado, cliente, motivonocompra);
        }
        
        public string ActualizarPosicionTest(string usuario, string fecha, string lat, string lng, int estado, string cliente, int motivonocompra, string pesos, int bultos) {
            return base.Channel.ActualizarPosicionTest(usuario, fecha, lat, lng, estado, cliente, motivonocompra, pesos, bultos);
        }
        
        public int ActualizarLastDownload(string imei, string fecha) {
            return base.Channel.ActualizarLastDownload(imei, fecha);
        }
        
        public int ActualizarLastDownloadATodas(string fecha) {
            return base.Channel.ActualizarLastDownloadATodas(fecha);
        }
        
        public System.Data.DataTable ObtenerPosicionActualPreventistas() {
            return base.Channel.ObtenerPosicionActualPreventistas();
        }
        
        public System.Data.DataTable ObtenerPosicionesDelPreventista(string usuario, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            return base.Channel.ObtenerPosicionesDelPreventista(usuario, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataTable ObtenerVendedoresPorDia(System.DateTime fechaDesde, System.DateTime fechaHasta) {
            return base.Channel.ObtenerVendedoresPorDia(fechaDesde, fechaHasta);
        }
        
        public System.Data.DataTable ObtenerPrimerClienteVisitado(string usuario, System.DateTime fechaDesde, System.DateTime fechaHasta) {
            return base.Channel.ObtenerPrimerClienteVisitado(usuario, fechaDesde, fechaHasta);
        }
        
        public System.Data.DataTable ObtenerPreventistasPorEmpresa(string empresa) {
            return base.Channel.ObtenerPreventistasPorEmpresa(empresa);
        }
        
        public string SubirFotoCliente(string usuario, string cliente, string foto) {
            return base.Channel.SubirFotoCliente(usuario, cliente, foto);
        }
    }
}
